import type { Metadata } from "next";

export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL || "https://vibeongo.com"
).replace(/\/$/, "");

export const SITE_NAME = "VibeOnGo";

export const SITE_TAGLINE = "Cloud workspaces for AI coding agents";

export const SITE_DESCRIPTION =
  "Launch isolated, agent-ready cloud workspaces for Codex, OpenCode, Pi and T3 Code — with persistent terminals, live HTTPS previews, automations, built-in Forgejo and an Android app.";

export const TWITTER_HANDLE = "@Jashandeep31";

export const SITE_KEYWORDS = [
  "cloud development environment",
  "AI coding agent",
  "cloud workspace",
  "remote development",
  "Codex",
  "OpenCode",
  "T3 Code",
  "coding agent sandbox",
  "live HTTPS preview",
  "Forgejo",
  "developer automation",
  "code from phone",
];

/** Legal pages change rarely; bump these when their content changes. */
export const LEGAL_LAST_UPDATED = {
  privacy: "2026-09-16",
  terms: "2026-09-16",
} as const;

export function absoluteUrl(path = "/") {
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}

/** Generated by app/opengraph-image.tsx; resolved against metadataBase. */
export const DEFAULT_OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "VibeOnGo — Give your agent a real computer. Cloud workspaces for AI coding agents.",
};

/**
 * Per-page metadata. Titles go through the root layout's template
 * ("%s — VibeOnGo"); canonical, Open Graph and Twitter stay in sync with the path.
 * A page-level `openGraph` replaces the inherited one wholesale, so the shared
 * OG image is passed explicitly here.
 */
export function pageMetadata({
  title,
  description,
  path,
  noIndex = false,
}: {
  title: string;
  description: string;
  path: string;
  noIndex?: boolean;
}): Metadata {
  const url = absoluteUrl(path);
  const fullTitle = `${title} — ${SITE_NAME}`;
  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      type: "website",
      locale: "en_US",
      url,
      siteName: SITE_NAME,
      title: fullTitle,
      description,
      images: [DEFAULT_OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      site: TWITTER_HANDLE,
      creator: TWITTER_HANDLE,
      title: fullTitle,
      description,
      images: [DEFAULT_OG_IMAGE.url],
    },
    ...(noIndex ? { robots: { index: false, follow: false } } : {}),
  };
}
